### ISSUE TITLE
Is this plugin stable?

### ISSUE THREAD

**Issue by SiliconEngine** [gdude2002/Python-Plugin-Loader#10]
I'm really happy to see someone running with the Python Plugin Loader project! But is it currently working? Your comments are a little contradictory, one part says to use decorations, another part says to use the class API, and another part says they're currently both broken. :)

How stable is the plugin right now? Thanks!

**Comment by gdude2002** [comment]
Well, @jomo over there appears to be using it in production. It certainly works - personally, I haven't used it myself in some time, but it worked when I forked it, aside from the fixes that were needed.

**Comment by SiliconEngine** [comment]
All right, I'll give it a shot and see how it goes. I used the Python Plugin Loader back in 2013 and it worked really well then. Thanks again!

**Comment by jomo** [comment]
There is this issue #1, however it seems to be limited to some specific use cases and you can work around it by double-checking the event type. As long as you use the decorator API you should be all good. The class API is outdated, read through the discussion in #1 for some details.

We've been using this plugin for years without any problems [here](https://github.com/RedstonerServer/redstoner-utils/) and more recently [here [wip]](https://github.com/RedstonerServer/toolbox/branches).
