### ISSUE TITLE
Reload scripts

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [gdude2002/Python-Plugin-Loader#12]
Please add the ability to reload plugins without having to restart the entire server.

**Comment by gdude2002** [comment]
Bukkit is very poorly-equipped to deal with reloading. There are many reasons why reloading any Bukkit plugin can cause a lot of issues and server instability, so I would advise against this sort of thing in any capacity.

**Comment by jomo** [comment]
You can always use `/reload`, however it's very buggy and shouldn't be used in production as @gdude2002 pointed out.
